name: CI

on:
  pull_request:
    paths:
      - 'protocol/near/**'

jobs:
  CI:
    name: Near CI
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # NEAR interface
      - name (NEAR Interface) Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: near-interface-nvm
        working-directory: ./protocol/near/near-interface

      - name: (NEAR Interface) Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.near-interface-nvm.outputs.NVMRC }}'

      - name: (NEAR Interface) Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./protocol/near/near-interface

      # NEAR borsh-wrapper
      - name: (NEAR Borsh wrapper) Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: near-borsh-wrapper-nvm
        working-directory: ./protocol/near/borsh-wrapper

      - name: (NEAR Borsh wrapper) Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.near-borsh-wrapper-nvm.outputs.NVMRC }}'

      - name: (NEAR Borsh wrapper) Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./protocol/near/borsh-wrapper

      - name: (NEAR Borsh wrapper) Build
        run: yarn build
        working-directory: ./protocol/near/borsh-wrapper

      # NEAR plugin
      - name: (NEAR Plugin) Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: near-plugin-nvm
        working-directory: ./protocol/near/plugin-js

      - name: (NEAR Plugin) Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.near-plugin-nvm.outputs.NVMRC }}'

      - name: (NEAR Plugin) Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./protocol/near/plugin-js

      - name: (NEAR Plugin) Build
        run: yarn build
        working-directory: ./protocol/near/plugin-js

      - name: (NEAR Plugin) Test
        run: yarn test
        working-directory: ./protocol/near/plugin-js
      #

      # NEAR wrapper
      - name: (NEAR Wrapper) Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: near-wrapper-nvm
        working-directory: ./protocol/near/wrapper

      - name: (NEAR Wrapper) Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.near-wrapper-nvm.outputs.NVMRC }}'

      - name: (NEAR Wrapper) Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./protocol/near/wrapper

      - name: (NEAR Wrapper) Build
        run: yarn build
        working-directory: ./protocol/near/wrapper

      - name: (NEAR Wrapper) Test
        run: yarn test
        working-directory: ./protocol/near/wrapper
