name: Publish-Substrate-Docker

# on:
#   push:
#     branches:
#     - main
#     paths:
#     - 'protocol/substrate/test-env/**'

on: [pull_request] # change this once the image has been created for the first time


jobs:
  Publish:
    name: Substrate Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./protocol/substrate/test-env
          push: true
          tags: |
            ghcr.io/chainsafe/integrations/substrate-polywrap-test-env:latest
