name: CI

on:
  pull_request:
    paths:
      - 'protocol/tezos/**'

jobs:
  CI:
    name: Tezos CI
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: tezos-nvm
        working-directory: ./protocol/tezos/tezos-domains-wrapper

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.tezos-nvm.outputs.NVMRC }}'

      - name: (Tezos) Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./protocol/tezos/test-env

      - name: Test up
        run: npm run test:env:up
        working-directory: ./protocol/tezos/test-env
        env:
          TEZOS_POLYWRAP_PORT: 20000
          TEZOS_POLYWRAP_BLOCK_TIME: 5
          TEZOS_POLYWRAP_PROTOCOL: Hangzhou
          TEZOS_POLYWRAP_PLATFORM: linux/amd64
          TEZOS_POLYWRAP_ROOT_PATH: /

      - name: Test down
        run: npm run test:env:down
        working-directory: ./protocol/tezos/test-env
        env:
          TEZOS_POLYWRAP_PORT: 20000
          TEZOS_POLYWRAP_BLOCK_TIME: 5
          TEZOS_POLYWRAP_PROTOCOL: Hangzhou
          TEZOS_POLYWRAP_PLATFORM: linux/amd64
          TEZOS_POLYWRAP_ROOT_PATH: /
      #